Sikorsky Alexandr/2/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :ingestions, only: %i[index new create update edit destroy]
  resources :dishes
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :charts do
    get 'average-calories'
    get 'ingestions-count'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Sikorsky Alexandr/2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Sikorsky Alexandr/2/app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :calorie_value, presence: true, numericality: true

  has_many :ingestions
  has_and_belongs_to_many :ingestions
  # has_many :users, through: :ingestions
end

Sikorsky Alexandr/2/app/models/ingestion.rb
class Ingestion < ApplicationRecord
  validate :date_cannot_be_in_the_future
  
  belongs_to :user
  has_and_belongs_to_many :dishes

  def date_cannot_be_in_the_future
    if time.present? && time > Date.today
      errors.add(:time, "can't be in the future")
    end
  end
end

Sikorsky Alexandr/2/app/models/user.rb
class User < ApplicationRecord
  has_many :ingestions
  has_many :dishes, through: :ingestions
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Sikorsky Alexandr/2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

Sikorsky Alexandr/2/app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :ingestions_data

  def ingestions_count
    render json: ingestions_data.count
   end

  def average_calories
    render json: ingestions_data.joins(:dishes).sum(:calorie_value)
  end

  private

  def ingestions_data
    @ingestions_data ||= begin
      range = 7.days.ago..Time.now
      current_user.ingestions.group_by_day(:time, range: range)
    end
  end
end

Sikorsky Alexandr/2/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show; end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit; end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dish
    @dish = Dish.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dish_params
    params.require(:dish).permit(:name, :weight, :calorie_value, :proteins, :carbohydrates, :fats)
  end
end

Sikorsky Alexandr/2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

Sikorsky Alexandr/2/app/controllers/ingestions_controller.rb
class IngestionsController < ApplicationController
  before_action :set_ingestion, only: %i[edit update destroy]

  def index
    @ingestions = current_user.ingestions
  end

  def new
    @ingestion = Ingestion.new
  end

  def edit; end

  def create
    @ingestion = current_user.ingestions.new(ingestion_params)

    ingestion_params['dish_ids'].reject(&:empty?).each do |dish_id|
      dish = Dish.find(dish_id)
      @ingestion.dishes << dish
    end

    respond2create(@ingestion.save)
  end

  def update
    @ingestion.time = ingestion_params[:time]
    @ingestion.dishes.clear
    add_dishes

    respond2update(@ingestion)
  end

  def destroy
    @ingestion.destroy

    redirect_to ingestions_path, notice: 'ingestion was successfully destroyed.'
  end

  private

  def add_dishes
    ingestion_params['dish_ids'].reject(&:empty?).each do |dish_id|
      dish = Dish.find(dish_id)
      @ingestion.dishes << dish
    end
  end

  def set_ingestion
    @ingestion = Ingestion.find(params[:id])
  end

  def respond2create(save_result)
    if save_result
      redirect_to ingestions_path, notice: 'ingestion was successfully added.'
    else
      render :new
    end
  end

  def respond2update(save_result)
    if save_result
      redirect_to ingestions_path, notice: 'ingestion was successfully updated.'
    else
      render :edit
    end
  end

  def ingestion_params
    @ingestion_params ||= params.require(:ingestion).permit(:time, dish_ids: [])
  end
end

Sikorsky Alexandr/2/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :weight, :height, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :weight, :height, :password, :password_confirmation, :current_password)
  end
end

Sikorsky Alexandr/2/app/helpers/application_helper.rb
module ApplicationHelper
end

Sikorsky Alexandr/2/app/helpers/dishes_helper.rb
module DishesHelper
end

Sikorsky Alexandr/2/app/helpers/ingestions_helper.rb
module IngestionsHelper
  def total_calories(ingestion)
    return if ingestion.dishes.empty?

    calorie_values = ingestion.dishes.map(&:calorie_value).compact
    calorie_values.inject(&:+)
  end

  def dishes2str(ingestion)
    return if ingestion.dishes.empty?

    ingestion.dishes.map(&:name).join(', ')
  end
end

Sikorsky Alexandr/2/app/views/dishes/_form.html.slim
= bootstrap_form_for @dish do |f|
  - if @dish.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dish.errors.count, "error")} prohibited this dish from being saved:"
      ul
        - @dish.errors.full_messages.each do |message|
          li = message

  = f.text_field :name
  = f.number_field :weight
  = f.number_field :calorie_value
  = f.number_field :proteins
  = f.number_field :carbohydrates
  = f.number_field :fats
  .actions = f.submit

Sikorsky Alexandr/2/app/views/dishes/edit.html.slim
h1 Editing dish

== render 'form'

=> link_to 'Show', @dish
'|
=< link_to 'Back', dishes_path

Sikorsky Alexandr/2/app/views/dishes/index.html.slim
h1 Dishes
br
.container-fluid
  table.table-striped.table-wrapper-scroll {width="100%"}
    thead
      tr
        th Name
        th Weight
        th Calorie value
        th Proteins
        th Carbohydrates
        th Fats
        th
        th
        th

    tbody
      - @dishes.each do |dish|
        tr
          td = dish.name
          td = dish.weight
          td = dish.calorie_value
          td = dish.proteins
          td = dish.carbohydrates
          td = dish.fats
          td = link_to '<button class="btn btn-info">Show</button>'.html_safe, dish
          td = link_to '<button class="btn btn-secondary">Edit</button>'.html_safe, edit_dish_path(dish)
          td = link_to '<button class="btn btn-danger">Destroy</button>'.html_safe, dish, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to '<button class="btn btn-primary">New dish</button>'.html_safe, new_dish_path

Sikorsky Alexandr/2/app/views/dishes/new.html.slim
h1 New dish

== render 'form'

= link_to 'Back', dishes_path

Sikorsky Alexandr/2/app/views/dishes/show.html.slim
.jumbotron
  h3
    strong = @dish.name.capitalize
  p
    strong Weight:
    = @dish.weight
  p
    strong Calorie value:
    = @dish.calorie_value
  p
    strong Proteins:
    = @dish.proteins
  p
    strong Carbohydrates:
    = @dish.carbohydrates
  p
    strong Fats:
    = @dish.fats

  => link_to '<button class="btn btn-primary">edit</button>'.html_safe, edit_dish_path(@dish)

  =< link_to '<button class="btn btn-secondary">back</button>'.html_safe, dishes_path

Sikorsky Alexandr/2/app/views/home/index.html.slim
.container
  h2 average daily calories
  = line_chart charts_average_calories_path
.container 
  h2 daily ingestions count
  = line_chart charts_ingestions_count_path

Sikorsky Alexandr/2/app/views/ingestions/_form.html.slim
= bootstrap_form_for @ingestion do |f|
  - if @ingestion.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ingestion.errors.count, "error")} prohibited this dish from being saved:"
      ul
        - @ingestion.errors.full_messages.each do |message|
          li = message
  = f.collection_select(:dish_ids, Dish.all, :id, :name, {}, {:multiple => true, :class => 'form-control'})
  = f.datetime_select :time 
  .actions = f.submit

Sikorsky Alexandr/2/app/views/ingestions/edit.html.slim
= render 'form'
br
= link_to '<button class="btn btn-secondary">Back</button>'.html_safe, ingestions_path

Sikorsky Alexandr/2/app/views/ingestions/index.html.slim
h1 Ingestions
.container-fluid
  table.table-striped.table-wrapper-scroll {width="100%"}
    thead
      tr
        th Time
        th Dishes
        th Calorie value
        th 
        th 

    tbody
      - @ingestions.each do |ingestion|
        tr
          td = ingestion.time.strftime('%F %H:%M') 
          td = dishes2str(ingestion)
          td = total_calories(ingestion)
          td = link_to 'Edit', edit_ingestion_path(ingestion)
          td = link_to 'Destroy', ingestion, data: { confirm: 'Are you sure?' }, method: :delete
br

= link_to '<button class="btn btn-primary">new</button>'.html_safe , new_ingestion_path

Sikorsky Alexandr/2/app/views/ingestions/new.html.slim
= render 'form'
br
= link_to '<button class="btn btn-secondary">Back</button>'.html_safe, ingestions_path

Sikorsky Alexandr/2/app/views/layouts/_nav.html.slim
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        = link_to "home", root_path, class: 'nav-link'
      </li>
      <li class="nav-item">
         = link_to "journal", ingestions_path, class: 'nav-link'
      </li>
      <li class="nav-item">
        = link_to "dishes", dishes_path, class: 'nav-link'
      </li>
    </ul>
  </div>
  - if current_user
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          = link_to "edit user",  edit_user_registration_path,  class: 'nav-link'
        </li>
        <li class="nav-item">
          = link_to "sign out", destroy_user_session_path, method: 'delete',  class: 'nav-link'
        </li>
        
      </ul>
    </div>
</nav>

Sikorsky Alexandr/2/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AmazingCalorieCounter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/nav'
    .container
      - if notice 
        .alert.alert-success { role="alert" }
          A = notice
      = yield
    footer.footer
      .container
        span &copy; #{ Date.today.year } Sikorsky inc.